### ISSUE TITLE
Indented, collapsible tree with +/- boxes, icons, labels next to icon and labels on links

### ISSUE THREAD

**Issue by brettforbes** [EE2dev/hierarchy-explorer#11]
Hi,

I want to build a D3 collapsible indented tree that looks like old-school type file explorer tree, with:
- plus/minus marks in boxes to indicate collapsible/expandable
- gridlines marking the indents
- icons/images at the end of each line
- labels to the right of each icon/image
- labels on the links if possible

![image](https://github.com/EE2dev/d3-indented-tree/assets/24556510/d85db210-8820-4089-a3d7-14d6a175798f)

Can i do this using your package? If so, how?

**Comment by EE2dev** [comment]
> Hi,
> 
> I want to build a D3 collapsible indented tree that looks like old-school type file explorer tree, with:
> 
> plus/minus marks in boxes to indicate collapsible/expandable

In general, each node can consist of one icon and one label next to it. The default node icon is a box with a plus sign if expandable and empty if it is a leaf.
See e.g. https://blocks.roadtolarissa.com/EE2dev/423d4e8c040bed8d96e9b72e65ae8999

You can substitute the default node icon with a custom vector or raster graphic icon. So you can reference the two folder icons (one when expanded, one when it is a leaf). But then you don't have the box with the plus sign any more.
The only way to achieve both is create an icon which contains both the box and the little image. 

> gridlines marking the indents

yes, that is the default

> icons/images at the end of each line

as mentioned above, one icon is displayed at the beginning of each line.

> labels to the right of each icon/image

yes that is the default

> labels on the links if possible

yes, you can label the links based on your data

Here I added two examples to roughly display what you described:

1.  https://blocks.roadtolarissa.com/EE2dev/71d6d17bc016e4037350158c2875893f
2.  (and with labeled links): https://blocks.roadtolarissa.com/EE2dev/d6ad615b0197c2813fc231d2784fd6c9
